Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!\p"
    .string "I saw some wild stuff.\n"
    .string "MIKE JONES! WHO!? MIKE JONES!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "I saw you in VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "There are other kinds of POKéMON\n"
    .string "than the ones you find in forests.$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "Are you using a POKéMON CENTER's\n"
    .string "PC for storing your POKéMON?\p"
    .string "Each BOX can hold up to\n"
    .string "30 POKéMON.$"

Route3_Text_JaniceIntro::
    .string "Hello!\n"
    .string "It's a pleasure to meet you.$"

Route3_Text_JaniceDefeat::
    .string "You're mean!$"

Route3_Text_JanicePostBattle::
    .string "Somtimes, maybe often, looks\n"
    .string "can be deceiving.$"

Route3_Text_GregIntro::
    .string "HOWDY TRAINER!!\n"
    .string "Let's get down to acion!$"

Route3_Text_GregDefeat::
    .string "YIKES, bested by a rich dwarf.\n"
    .string "A strong, rich dwarf. :D$"

Route3_Text_GregPostBattle::
    .string "If a POKéMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"

Route3_Text_SallyIntro::
    .string "Do you admire modesty?\n"
    .string "Are YOU modest!?$"

Route3_Text_SallyDefeat::
    .string "The modes thing to do is lose.$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "How do I know you're kewl??$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Like a peanut out a bag.$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. I'm the breezy type. ;)$"

Route3_Text_JamesIntro::
    .string "Everyone watch me spank this pygmy\n"
    .string "with  POKéMON I just caught.$"

Route3_Text_JamesDefeat::
    .string "I guess I shouldn't have\n"
    .string "tried to draw a crowd.$"

Route3_Text_JamesPostBattle::
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Are they wearing shorts?$"

Route3_Text_RobinDefeat::
    .string "Well done young lad of the poke.$"

Route3_Text_RobinPostBattle::
    .string "ROUTE 4 is at the foot of\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"

