ViridianForest_Text_RickIntro::
    .string "Hello, Let us trai!\n"
    .string "our PokeMon.\l"
    .string "Let's test 'em and us!$"

ViridianForest_Text_RickDefeat::
    .string "No!\nCATERPIE can't hack it!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?\p"
    .string "--MASSIVE ECHOING FART--\n"
    .string "FWAMPPPPSQUEEEEKKKKPOP$"

ViridianForest_Text_DougIntro::
    .string "Greetings future sage!\n"
    .string "Let us communicate the way\p"
    .string "POKéMON TRAINERs do!$"

ViridianForest_Text_DougDefeat::
    .string "Congrats! And thank you for\n"
    .string "the practice for my POKéMON!$"

ViridianForest_Text_DougPostBattle::
    .string "Losses teach us. I'm going to\n"
    .string "catch some stronger POKeMON!\p"
    .string "Also, JUST GYI, you smell\n"
    .string "absolutely atrocious. :X$"

ViridianForest_Text_SammyIntro::
    .string "What it do babyyy?\n"
    .string "I say baby because you're small.$"

ViridianForest_Text_SammyDefeat::
    .string "Yikes!\n"
    .string "I lost to a toddler!$"

ViridianForest_Text_SammyPostBattle::
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "Can you look around...\n"
    .string "for DEEZ NUTS!!!!$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be a noob, but\n"
    .string "don't go easy on me!$"

ViridianForest_Text_AnthonyDefeat::
    .string "I will train...\n"
    .string "Then whoop you like\p"
    .string "I'm you're dad!!!$"

ViridianForest_Text_AnthonyPostBattle::
    .string "I heard someone soil their pants.$"

ViridianForest_Text_CharlieIntro::
    .string "Scrambled eggs if you please.$"

ViridianForest_Text_CharlieDefeat::
    .string "Turds and gravy!\n"
    .string "I'm not good with losing. :($"

ViridianForest_Text_CharliePostBattle::
    .string "A true gent\n"
    .string "never is caught passing gas.$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I wish I was as brave as you,\n"
    .string "I would love to train with\p"
    .string "MASTER THAY! YOU'RE SO LUCKY!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRAINER TIPS\p"
    .string "You encounter wild POKeMON\n"
    .string "in tall grasses.\p"
    .string "If your POKeMON are weak,\n"
    .string "consider avoding these areas.$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "For poison, use ANTIDOTE!\n"
    .string "Get it at POKéMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "TRAINER TIPS\p"
    .string "Contact MASTER THAY via a PC to\n"
    .string "get your POKéDEX evaluated!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAINER TIPS\p"
    .string "You can't catch a POKéMON that\n"
    .string "belongs to someone else.\p"
    .string "Throw POKé BALLS only at wild\n"
    .string "POKéMON to catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TRAINER TIPS\p"
    .string "Weakening POKeMON, either by\n"
    .string "reducing their HP or inflicting\l"
    .string "statusus such as sleep or paralysis,\l"
    .string "increases your catch rate."

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"

