PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What!?\p"
    .string "TEAM ROCKET is at MT. MOON?\n"
    .string "Huh?\p"
    .string "I'm on the phone!\n"
    .string "OUT MY FACE, PRICK!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "I really want a PIKACHU, so I'm\n"
    .string "trading my CLEFAIRY for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "I'm trading POKéMON with that kid\n"
    .string "there.\p"
    .string "I had two PIKACHU, so I figured\n"
    .string "I might as well trade one.$"

