Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "Often it is the ugly that is\n"
    .string "the impetus for beauty."

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "Welcome to PEWTER CITY!\p"
    .string "Though the forest is mostly bugs\n"
    .string "our GYM LEADER is known for using\p"
    .string "ROCK POKeMON.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "I will show you it now!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "This is it, the MUSEUM.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. Byb, pip squeek!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "You're a TRAINER, right?\p"
    .string "BROCK's looking for GYM\n"
    .string "challengers. Let's go!$"

PewterCity_Text_GoTakeOnBrock::
    .string "Believe in yourself,\n"
    .string "and go take on BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
    .string "All POKéMON that appear in battle,\n"
    .string "however briefly, earn EXP Points.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from MT. MOON.\p"
    .string "Please call the PEWTER POLICE if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I help out MASTER THAY.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Press the B Button to run.\n"
    .string "But only where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "HOME.\p"
    .string "Bye, {PLAYER}!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "I know that starting out on\n"
    .string "something new can be scary.\p"
    .string "You may feel lonely or inadequate\n"
    .string "at times. But please know that\p"
    .string "I am always there for you. When\n"
    .string "times are hard, just think of me\p"
    .string "and remember that I love you\n"
    .string "and always will, no matter what.\p"
    .string "I will always be fighting for you.\n"
    .string "I hope you enjoy the fancy SHOES!\p"
    .string "Love MOM$"


PewterCity_TEXT_INTEROSPECTION::
    .string "{PLAYER}:----THOUGHTS-------\p"
    .string "Though we are young, it's been\n"
    .string "quite a tale already.\p"
    .string "One thing that I have noticed\n"
    .string "is how how nice most people are\p"
    .string "when you are nice to them.\n"
    .string "I am surprised at how hard\p"
    .string "many people's lives are.\n"
    .string "I wish I could help...$"

PewterCity_Text_ASK_SET_FLAG::
    .string "Those are my thoughts so far.\p"
    .string "Would you like to hear {PLAYER}'s\n"
    .string "thoughts going forward?$"
