Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.\p"
    .string "Also, sometimes people will\n"
    .string "give you information on\l"
    .string "the TRAINERS in the area.\p"
    .string "I hope this helps:\n"
    .string "there is a strong TRAINER ahead.\p"
    .string "they have Pokemon ranging from\n"
    .string "lvl. 9 to 10\l"
    .string "with a KANGASKHAN to note.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "You can jump from them\n"
    .string "to get back to PALLET TOWN;\l"
    .string "it's quicker that way.\p"
    .string "Also, if you're not careful\n"
    .string "someone like me might...\l"
    .string "shove you off one, rich kid.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"



