PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: I love you very much, {PLAYER}.\n"
    .string "I hope you know that no matter\l"
    .string "where you go you always\l"
    .string "have someone that\l"
    .string "cares for you and\l"
    .string "wants to see you happy.\p"
    .string "This bring me to my main point:\n"
    .string "I am proud of your brave decision\l"
    .string "to join Master Thay's monastery.\p"
    .string "Although the journey may be\n"
    .string "difficult, I know that you\l"
    .string "will become a great monk.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: I love you very much, {PLAYER}.\n"
    .string "I hope you know that no matter\l"
    .string "where you go you always\l"
    .string "have someone that\l"
    .string "cares for you and\l"
    .string "wants to see you happy.\p"
    .string "This bring me to my main point:\n"
    .string "I am proud of your brave decision\l"
    .string "to join Master Thay's monastery.\p"
    .string "Although the journey may be\n"
    .string "difficult, I know that you\l"
    .string "will become a great nun.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

