ViridianCity_House_Text_NicknamingIsFun::
    .string "Do not ask me how I am\n"
    .string "for I neither care nor know."

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "My daddy has been listening\n"
    .string "to talks by MASTER THAY.\p"
    .string "I don't understand them,\n"
    .string "but I like that it makes\p"
    .string "my daddy happy."

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Name: SPEARY$"

